export const SEARCH = 'SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const CLEAR_SORT = 'CLEAR_SORT';
export const SORT_BY_HIGHEST_PRICE = 'SORT_BY_HIGHEST_PRICE';
export const SORT_BY_LOWEST_PRICE = 'SORT_BY_LOWEST_PRICE';
export const SORT_BY_ASCENDING_NAME = 'SORT_BY_ASCENDING_NAME';
export const SORT_BY_DESCENDING_NAME = 'SORT_BY_DESCENDING_NAME';

export const FILTER_BY_CATEGORY_NAME = 'FILTER_BY_CATEGORY_NAME';
export const FILTER_BY_RATING_VALUE = 'FILTER_BY_RATING_VALUE';

export const APPLIED_FILTER_TYPE = {
  SEARCH: 1,
  SORT: 2,
  FILTER: 3,
};
