export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const FILTER_ACTIVE = 'FILTER_ACTIVE';
export const SORT_ACTIVE = 'SORT_ACTIVE';
export const SEARCH_ACTIVE = 'SEARCH_ACTIVE';
export const CLEAR_FILTER = 'CLEAR_FILTER';
